US_FL_jacksonville
skedgo/regions pull request #19
Opened 2022-10-03 16:45 UTC by ManuBenito259

2022-10-05 19:13 UTC, fersagui requested changes

2022-10-05 19:13 UTC, fersagui commented on regions/us-fl-jacksonville.json
> +      "coordinates": [
@ManuBenito259 could you change this polygon to be next to the actual US_FL_Orlando polygon? 
<img width="446" alt="Screen Shot 2022-10-05 at 16 08 37" src="https://user-images.githubusercontent.com/1991758/194142629-945a6024-d536-4ef5-be8a-16f70a29d45a.png">

2022-10-05 19:13 UTC, fersagui commented on regions/us-fl-jacksonville.json
> +    "us-jta"
Could you check if there are not other sources of data on this area? I have found this one too: https://transitfeeds.com/l/407-st-augustine-fl-usa

2022-10-05 23:39 UTC, ManuBenito259 commented on regions/us-fl-jacksonville.json
> +      "coordinates": [
On it, should they overlap?

2022-10-06 12:25 UTC, fersagui commented on regions/us-fl-jacksonville.json
> +      "coordinates": [
yes, just a few. We could add services that connects both areas if there are any.

2022-10-06 14:13 UTC, ManuBenito259 commented on regions/us-fl-jacksonville.json
> +    "us-jta"
![imagen](https://user-images.githubusercontent.com/53844861/194335479-dfa2ad29-e622-4a49-bcdf-2b45f6610470.png)


Only JTA and St. Augustine's Sunshine Bus according to transit land

2022-10-06 17:36 UTC, fersagui approved these changes
LGTM

2022-10-06 17:36 UTC, merged

2022-10-06 17:37 UTC, fersagui commented on regions/us-fl-jacksonville.json
> +    "us-jta"
Ok, thanks for the feedback