Validator Draft
skedgo/regions pull request #2
Opened 2022-09-05 19:05 UTC by damianVarela

This is just a draft for a validator. Lots of things need tbd yet.

2022-09-05 20:20 UTC, nighthawk requested changes
Please move files back and also add a README for how to run the validator.

2022-09-05 20:20 UTC, nighthawk commented on src/main/resources/schema/feed.schema.json
>  {
Please move the schema files back to their original location, so that they are easily accessible and not tied to the validator. You can soft-link them to this location, is the validator needs to have them in the code base.

Also, we need a PR to review the specs as there are various things they should be improved with them as they seem closely tied to our Region.java implementation.

2022-09-05 20:20 UTC, nighthawk commented on src/main/resources/schema/region.schema.json
>  {
Move this file back, too

2022-09-05 22:45 UTC, damianVarela commented on src/main/resources/schema/feed.schema.json
>  {
@nighthawk wrote:
>Please move the schema files back to their original location
done (in merge) -> https://github.com/skedgo/regions/pull/2/commits/f8c08008c0c522c2891896f575dc5d7aa8335b76

>You can soft-link them to this location, is the validator needs to have them in the code base.
The validator needs the schema in order to validate an input. Yes. 

>Also, we need a PR to review the specs as there are various things they should be improved with them as they seem closely tied to our Region.java implementation.

done -> https://github.com/skedgo/regions/pull/4

2022-09-05 22:47 UTC, damianVarela commented
rebasing this one to https://github.com/skedgo/regions/pull/4

2022-09-07 19:21 UTC, damianVarela commented
@nighthawk wrote:
>Please ... and also add a README for how to run the validator.

For now it is `./mvnw test`. But I guess that it will change.

2022-09-12 21:39 UTC, nighthawk requested changes
Minor requested change in comment. Please update the README with instructions for how to use the validator.

Ideally also add a GitHub Action already which runs on the feeds you're adding, too.

2022-09-12 21:39 UTC, nighthawk commented on publictransportfeeds/ar-bacolectivos.json
> +{
Can you rename the folders to match the specs file, just as plural?

- `pt-static-feeds`
- `pt-realtime-feeds`
- `regions`

2022-09-12 21:46 UTC, nighthawk commented
Should we move the Java stuff one level down and into a folder that explains what it is, e.g., "Validator"?

2022-09-12 21:47 UTC, nighthawk commented
> Should we move the Java stuff one level down and into a folder that explains what it is, e.g., "Validator"?

The repo is about primarily the regions and the specs, so makes sense to move helper things like the validator and its java/maven stuff out of the root, to keep this a bit tidier.

There might be other tools coming as part of the repo, so maybe put it into `tools/Validator`?

2022-09-12 22:35 UTC, damianVarela commented
@nighthawk wrote:

>The repo is about primarily the regions and the specs, so makes sense to move helper things like the validator and its java/maven stuff out of the root, to keep this a bit tidier.
>There might be other tools coming as part of the repo, so maybe put it into tools/Validator?

Well, I asked for some feedback to @MarianoTucat in here -> https://redmine.buzzhives.com/issues/17735?tab=history#note-4
No answer so far. 

My concern is how we are going to keep the validator from being modified. Is that even possible? If we keep all in the same repo, anyone can modify everything. The specs, the json files, the validator and even the GHA definitions. Perhaps we should circle back to this concern later.

2022-09-12 22:36 UTC, damianVarela commented on publictransportfeeds/ar-bacolectivos.json
> +{
done -> https://github.com/skedgo/regions/pull/2/commits/6f14c6161e5ddf31523ebd1473682e707794e6d1

2022-09-12 23:09 UTC, nighthawk commented
> My concern is how we are going to keep the validator from being modified. Is that even possible?

That's not really an issue. Anyone can fork the repo and modify the code, but this is the canonical repo which we control. Changes can only be made via PRs, which only our maintainers can merge.

2022-09-12 23:45 UTC, damianVarela commented
@nighthawk wrote:
>There might be other tools coming as part of the repo, so maybe put it into tools/Validator?

done -> https://github.com/skedgo/regions/pull/2/commits/f2e8d093e2218feb570a3936991e07a14caf4286

2022-09-12 23:49 UTC, nighthawk commented on pt-realtime-feeds/ar-babusrt.json
> +    "url": "https://apitransporte.buenosaires.gob.ar/colectivos/vehiclePositions?client_id=d3d3c80dc41a40dbb13dc2654c9e01ca&client_secret=048bcD1A07DD4F32BdF0AdC5D46456af"
The client ID and client secret should be removed and replaced with instructions for how to get them

2022-09-12 23:49 UTC, nighthawk commented on pt-static-feeds/ar-bacolectivos.json
> +    "url": "https://apitransporte.buenosaires.gob.ar/colectivos/feed-gtfs?client_id=d3d3c80dc41a40dbb13dc2654c9e01ca&client_secret=048bcD1A07DD4F32BdF0AdC5D46456af",
Same here, please remove credentials

2022-09-12 23:49 UTC, nighthawk commented on regions/ar_b_bahiablanca.json
> +      "lng": 0,
Wrong lat/lng, does the validator catch this?

2022-09-13 00:02 UTC, damianVarela commented on regions/ar_b_bahiablanca.json
> +      "lng": 0,
Actually, they are not wrong. (0,0) are valid coordinates near Africa.

2022-09-13 00:04 UTC, damianVarela commented on regions/ar_b_bahiablanca.json
> +      "lng": 0,
Although... one thing we can do is to check that all cities and locations are contained in the defined polygon.

2022-09-13 03:18 UTC, nighthawk commented on regions/ar_b_bahiablanca.json
> +      "lng": 0,
We could check for that particular case it’s a common error and in the ocean.

2022-09-15 21:13 UTC, nighthawk approved these changes
LGTM

2022-09-16 00:34 UTC, merged