US-CA-Ventura
skedgo/regions pull request #24
Opened 2022-10-21 19:27 UTC by ManuBenito259

US-CA-Ventura regions and its feed us-vctc

2022-10-21 19:31 UTC, damianVarela approved these changes
fine by me as long as the validator doesn't fail.

2022-10-21 19:32 UTC, ManuBenito259 commented
I had forgotten this one thinking it had no feeds, will look for other available feeds on the area but opening the pr to begin testing on TC asap

2022-10-25 12:01 UTC, fersagui requested changes
Add any other operator which is in the area

2022-10-25 12:01 UTC, fersagui commented on regions/us-ca-ventura.json
> +    "us-vctc"
and this one: https://www.transit.land/feeds/f-santa~clarita/

2022-10-25 12:01 UTC, fersagui commented on regions/us-ca-ventura.json
> +          ]
This is touching LA polygon
![Screen Shot 2022-10-25 at 08 54 49](https://user-images.githubusercontent.com/1991758/197767207-9cfd655e-5e6b-4dc5-95cf-aede220cca9f.png). We have to be sure the area is covered well.

2022-10-26 20:07 UTC, ManuBenito259 commented on regions/us-ca-ventura.json
> +          ]
VCTC has routes going into Thousand Acres which is inside the LA polygon. The routes would be ecluded if the polygon is reduced, is that still correct?
![imagen](https://user-images.githubusercontent.com/53844861/198126307-5cfd8b7b-6d0c-44ab-98a2-8f77b7f3ad58.png)

2022-10-27 04:08 UTC, nighthawk commented on regions/us-ca-ventura.json
> +          ]
It's a good opportunity to make the LA region a little bit smaller by moving Thousand Oaks and Simi Valley into the new Ventura region.

> VCTC has routes going into Thousand Acres which is inside the LA polygon. The routes would be ecluded if the polygon is reduced, is that still correct?

No, they will not b excluded. Routes can extend outside a region's polygon into another region's. They will then be included in both regions.

2022-10-27 04:08 UTC, nighthawk commented on regions/us-ca-ventura.json
> +    "us-vctc"
Should probably also include the existing Thousand Oaks feed, too.

2022-10-27 23:56 UTC, fersagui commented on regions/us-ca-ventura.json
> +          ]
@nighthawk what about this configuration? <img width="818" alt="Screen Shot 2022-10-27 at 20 55 26" src="https://user-images.githubusercontent.com/1991758/198418796-e4c4b2b3-56a4-42c3-addf-d55bc9c52365.png">

2022-10-28 00:04 UTC, nighthawk commented on regions/us-ca-ventura.json
> +          ]
Looks good to me

2022-10-28 00:15 UTC, fersagui approved these changes
Polygon is now fixed and new sources added

2022-10-28 00:15 UTC, merged