Waupaca county region
skedgo/regions pull request #31
Opened 2022-11-22 18:38 UTC by ManuBenito259

2022-11-22 19:10 UTC, ManuBenito259 commented
tests will fail due to no gtfs added to the region

2022-11-23 12:35 UTC, fersagui requested changes
@ManuBenito259 please update the schema to allow regions without PT feeds.

2022-11-24 06:58 UTC, ManuBenito259 commented
The schema was updated

2022-11-24 13:22 UTC, fersagui approved these changes
Let's use this to create the hive for testing

2022-11-24 13:22 UTC, merged