Region and Feed schemas
skedgo/regions pull request #4
Opened 2022-09-05 22:19 UTC by damianVarela

- Add region schema.
- Add feed schema.

2022-09-05 23:34 UTC, nighthawk requested changes

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +  "description": "Feed specification.",
What does "Feed" mean?

Should we rename this to "Public Transport Data Feed"?

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +      "description": "Unique identifier for this feed.",
Should this be unique for just the region or globally? Can we have a guideline for what these should look like, e.g., "ISO country code + provider name"?

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +      "enum": ["gtfs", "netex", "txc", "coaches"],
Can this add links to where you can find more about these formats. And what is "coaches"?

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +          }
We might need a different way for dealing with this. Putting credentials into a JSON does not seem save, in particular a plain text password. Maybe this should instead specify that a username + password is needed, and where to get these, rather than hard-coding them.

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +          "description": "Enables timestamp checking between a preoviuos feed and the one from the external source.",
Not clear to me what this means.

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +        "sourceOfSource": {
`sourceOfSource` seems funny as this is _inside_ the source, could just be named `dataProvider` instead.

Might be good to also have an object in here, rather than just a string, with a name and a URL.

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +        }
This seems to be more of an implementation detail of what to do when fetching the feed, rather than being part of the region specification. Could this just be handled by the consumer of these specs, i.e., download it and name according to the extension in `url` and if that's not existent use `id` for the file name.

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +          "type": "boolean"
As this is optional, it should specify the default value.

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +        },
I don't understand what this means

2022-09-05 23:34 UTC, nighthawk commented on schemas/feed.schema.json
> +    },
Would be better to replace this with an object about which real-time to use, e.g., it could point at a different spec file and then have the ID in here.

(Also better to not abbreviate "real time" with "RT")

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +      "type": "string"
Should specify how these are constructed

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +      "description": "A Java valid time zone id.",
Isn't there an ISO standard we can use, rather than tying this to Java?

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +        },
Do we really need this? Also not clear what this would be.

Would be better to replace with an optional list of cities.

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +        }
This is missing. Should probably be a GeoJSON Polygon.

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +        },
Can we remove this? The consumer of the specs should be able to fetch this from the currency code.

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +        }
Same, could also be inferred by the consumer from the currency code

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +      "required" : [ "format" ]
Should require the currency code

```suggestion
      "required" : [ "code" ]
```

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +    "trafficHand": {
That's a funny name, how about this instead:

```suggestion
    "trafficRule": {
```

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +      "default": "rht"
Why not just name it left or right? Also shouldn't have a default.

```suggestion
      "description": "Traffic side on the road to keep to.",
      "enum": ["left", "right"]
```

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +    },
This shouldn't be part of the region spec, but handled by the registry, or as a different configuration file for the region distribution.

```suggestion
```

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +    },
Also shouldn't be part of the region spec, but rather handled by the region distribution. Not that everything in this repo is explicitly "open data" eligibility.

```suggestion
```

2022-09-05 23:34 UTC, nighthawk commented on schemas/region.schema.json
> +  "required": [ "code", "timezone", "locale", "coverage", "currency", "servers" , "feeds" ]
There might not be public transport in the area, which means `feeds` can be optional.

```suggestion
  "required": [ "code", "timezone", "locale", "coverage", "currency" ]
```

2022-09-06 12:14 UTC, MarianoTucat commented on schemas/feed.schema.json
> +          }
on the tsp connector, we added an [authentication](https://github.com/skedgo/TSP-connector-specs/blob/master/specs/src/main/java/com/skedgo/openapi/model/shared/Authentication.java) field, which listed whether it was `header`, `query` or `none`. I guess for this we will also need `user/pass` too. Then, we need a way  to store and pull such credentials

2022-09-06 13:51 UTC, damianVarela commented on schemas/feed.schema.json
> +      "description": "Unique identifier for this feed.",
@nighthawk wrote:
>Should this be unique for just the region or globally? Can we have a guideline for what these should look like, e.g., "ISO country code + provider name"?

Well... , `region` - `public transport data feed` is a many-to-many relation. So I would say globally, yes. We can define a format for these identifiers. Today, with all the json files for the regions we maintain, we share (quite often) the very same feed among several regions. FlixBus is a good example that is shared between several countries. We can define this as `eu-flixbus` in this new schema for example. Note that `EU` is not a valid ISO Country Code (afaik), just like the UK we are using. (We should use `GB` instead of `UK`).

Then, we can extend the validator software that checks for this format and that is unique.

Thoughts? Please, stop me if I'm overthinking this.

2022-09-06 14:07 UTC, damianVarela commented on schemas/feed.schema.json
> +      "enum": ["gtfs", "netex", "txc", "coaches"],
@nighthawk wrote:
>And what is "coaches"?

hehe, this is legacy. We used to have:

``` json
{
    "parser": "com.buzzhives.GisBuilder.OtherParsers.GreyhoundAustralia",
    "path": ["Coaches", "GreyhoundAustralia"],
    "sourceOfSource": "http://greyhound.com.au/service-info/pdf-timetables"
}
```
Just checked and I see we don't have support for this anymore.

removed -> https://github.com/skedgo/regions/pull/4/commits/19c2f5f957d4bcf91e054713a354769ae5e94541

>Can this add links to where you can find more about these formats.

You mean like... in the description or how?

2022-09-06 15:26 UTC, damianVarela commented on schemas/feed.schema.json
> +          "description": "Enables timestamp checking between a preoviuos feed and the one from the external source.",
removed -> https://github.com/skedgo/regions/pull/4/commits/adfe00101fdac383f4c722684ff4998f63c55bfa

2022-09-06 15:49 UTC, damianVarela commented on schemas/feed.schema.json
> +  "description": "Feed specification.",
do you want to change the name of the file as well?

2022-09-06 18:13 UTC, damianVarela commented on schemas/region.schema.json
> +      "description": "A Java valid time zone id.",
From the javadocs:
>The default set of data is supplied by the IANA Time Zone Database (TZDB). This has region IDs of the form '{area}/{city}', such as 'Europe/Paris' or 'America/New_York'. This is compatible with most IDs from [TimeZone](https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html).

So I guess we can require a time zone id from IANA TZDB instead. is that ok?

2022-09-06 18:30 UTC, damianVarela commented on schemas/region.schema.json
> +        },
This is the value that `Region#getDefaultLocation()` returns. I don't have enough information in order to decide if this is really needed. But I can see that that this value is currently being used in the `RegionsServlet`. Perhaps this is legacy and it is there just as backward compatibility. Anyway, I can see that some regions use the first of the cities.

done in -> https://github.com/skedgo/regions/pull/4/commits/c6824276d63d60e4a743e8a6bc51077b0b075f94

2022-09-06 18:34 UTC, damianVarela commented on schemas/region.schema.json
> +        },
done -> https://github.com/skedgo/regions/pull/4/commits/ab74e0a9e7237b24b4f649cac633cdd39da5dcb5

2022-09-06 18:35 UTC, damianVarela commented on schemas/region.schema.json
> +        }
done -> https://github.com/skedgo/regions/pull/4/commits/9d51120bf08e42bb6ba0983bbd5dc3d8ae84fb11

2022-09-06 18:36 UTC, damianVarela commented on schemas/region.schema.json
> +      "required" : [ "format" ]
done -> https://github.com/skedgo/regions/pull/4/commits/706f93ee3723914eff0dd40adcc8535d3c64b955

2022-09-06 18:48 UTC, damianVarela commented on schemas/region.schema.json
> +        }
done -> https://github.com/skedgo/regions/pull/4/commits/3c3584403c5db69f20a764fe6dd1892140b866b6

2022-09-06 18:51 UTC, damianVarela commented on schemas/feed.schema.json
> +        }
removed -> https://github.com/skedgo/regions/pull/4/commits/c6d8d584b79fe0edea0fc204450024c6a0f9bd4a

2022-09-06 18:55 UTC, damianVarela commented on schemas/feed.schema.json
> +        "sourceOfSource": {
done -> https://github.com/skedgo/regions/pull/4/commits/1ed0b4e6806191c7282d6272923ac8e22ad9c8f8

2022-09-06 18:56 UTC, damianVarela commented on schemas/feed.schema.json
> +          "type": "boolean"
right! -> https://github.com/skedgo/regions/commit/fbd17506509d20ff317ec5857853750e80161a50

2022-09-06 18:58 UTC, damianVarela commented on schemas/feed.schema.json
> +        },
This is the `wiredLink` flag we have to identify all urls that needs to be paid extra attention. Should I remove this?

2022-09-06 19:16 UTC, damianVarela commented on schemas/region.schema.json
> +      "type": "string"
mmmm. yes. we can explain how to construct a code... or... we can enforce it. making this code an object that contains the country code, state/province/canton code and city name. something like:

``` json
"code (or something like id or idDetails)" : {
    "countryCode": "AU (this should be a valid ISO 3166-1 alpha-2 code)",
    "subdivisionCode": "NSW (this should be a valid ISO 3166-2 code)",
    "cityName": "Sydney"
}
```

then we can infer the actual region code.

thoughts?

2022-09-06 22:09 UTC, damianVarela commented on schemas/feed.schema.json
> +          }
This is just for clarification. As explained in the description, these credentials can be provided in the headers field. Should I remove this, so there's no confusion ?

2022-09-06 22:10 UTC, damianVarela commented on schemas/feed.schema.json
> +        },
This is not needed.

2022-09-06 22:16 UTC, damianVarela commented on schemas/feed.schema.json
> +    },
isn't public transport static data feed and real time feed a one-to-one relation? if so, then by normalization it should be included right here.

2022-09-07 00:46 UTC, nighthawk commented on schemas/feed.schema.json
> +          }
I think an authentication field would be good. Could be an object which has an authentication type enum (header, query, username+password) and a description field, where the description is just text to describe where to get the credentials and how to send them. If the field is not provided, it means "no authentication necessary".

2022-09-07 00:48 UTC, nighthawk commented on schemas/feed.schema.json
> +    },
It is not a one-to-one relationship. GTFS often has multiple GTFS-R feeds (one for vehicle positions, one for alerts, etc.), and occasionally a GTFS-R feed can be for multiple GTFS bundles (might be the case in Sydney). Similar might hold for NeTEx and SIRI, but I'm not sure about that.

2022-09-07 00:49 UTC, nighthawk commented on schemas/feed.schema.json
> +  "$id": "https://region-registry.skedgo.com/feed.schema.json",
Agree that we might want to rename this, e.g., `public-transport-feed.schema.json`, to differentiate from `shared-vehicle-feed.schema.json` and others down the track.

2022-09-07 00:50 UTC, nighthawk commented on schemas/feed.schema.json
> +      "description": "Unique identifier for this feed.",
Makes sense, so let's do global and recommend "ISO country code + provider" with an example, and where something like "eu" or "global" can be used for multi-country feeds.

Agree that we should use GB rather than UK.

2022-09-07 00:51 UTC, nighthawk commented on schemas/region.schema.json
> +      "type": "string"
Good idea, I like it.

2022-09-07 00:51 UTC, nighthawk commented on schemas/region.schema.json
> +      "description": "A Java valid time zone id.",
Sounds good

2022-09-07 00:54 UTC, nighthawk commented on schemas/region.schema.json
> +      "description": "A Java valid time zone id.",
Is this the same as what Linux has? I.e., what `timedatectl list-timezones` returns?

If not, maybe we should take the intersection of those two.

2022-09-07 00:55 UTC, nighthawk commented on schemas/region.schema.json
> +          "additionalProperties": false
What does this mean? Should we allow additional properties?

2022-09-07 00:55 UTC, nighthawk commented on schemas/region.schema.json
> +      "required": [ "defaultLocation", "polygon" ]
```suggestion
      "required": [ "cities", "polygon" ]
```

2022-09-07 00:56 UTC, nighthawk commented on schemas/region.schema.json
> +    },
Can now be simpliefied:

```suggestion
    "currencyCode": {
      "description": "The ISO 4217 currency code of this currency.",
      "type": "string"
    }, 
```

2022-09-07 00:57 UTC, nighthawk commented on schemas/region.schema.json
> +        "address": {
```suggestion
        "name": {
```

2022-09-07 00:57 UTC, nighthawk commented on schemas/region.schema.json
> +      "required": [ "lat", "lng", "address" ]
```suggestion
      "required": [ "lat", "lng", "name" ]
```

2022-09-07 00:58 UTC, nighthawk commented on schemas/region.schema.json
> +        "type": "string"
This should say what kind of string it is, i.e., what property in those PT feed JSON files.

2022-09-07 13:31 UTC, damianVarela commented on schemas/feed.schema.json
> +          }
done -> https://github.com/skedgo/regions/pull/4/commits/44cf1814398152ee3e98af765c9ba626865f5bf9

2022-09-07 14:15 UTC, damianVarela commented on schemas/region.schema.json
> +      "required": [ "defaultLocation", "polygon" ]
good catch!

2022-09-07 16:21 UTC, damianVarela commented on schemas/feed.schema.json
> +      "description": "Unique identifier for this feed.",
done -> https://github.com/skedgo/regions/pull/4/commits/f38778999cda67285b3e33d237a86e4c81e2e349

i've also added a pattern for validation. let me know if it is too restrictive.

2022-09-07 17:35 UTC, damianVarela commented on schemas/feed.schema.json
> +    },
done -> https://github.com/skedgo/regions/pull/4/commits/d45dd86f73f314ea454f9c78fba01ab41f178f93

i will create a `real-time-data-feed.schema.json` later

2022-09-07 17:49 UTC, damianVarela commented on schemas/region.schema.json
> +      "description": "A Java valid time zone id.",
@nighthawk wrote:
>Is this the same as what Linux has? I.e., what timedatectl list-timezones returns?

I did a quick reading about this and based on these two sections from this Wikipedia Articule [TZ Database -> Unix-like Systems](https://en.wikipedia.org/wiki/Tz_database#Unix-like_systems) and [TZ Database -> Use in software systems](https://en.wikipedia.org/wiki/Tz_database#Use_in_software_systems), it seems like it is indeed the same set. 

related changes in here -> https://github.com/skedgo/regions/pull/4/commits/3147f30d6c993c052ba4c8d9e375feb81fe87b96

2022-09-07 18:00 UTC, damianVarela commented on schemas/region.schema.json
> +          "additionalProperties": false
@nighthawk wrote:
>What does this mean?  Should we allow additional properties?

I means that this object cannot contain additional properties. In this context, we are saying that we require a strictly valid polygon. We can remove that restriction if you like.

2022-09-07 18:02 UTC, damianVarela commented on schemas/region.schema.json
> +        "type": "string"
done -> https://github.com/skedgo/regions/pull/4/commits/c2db86fe97f6ecd0e2578b1a543185f6e4215a17

2022-09-07 18:06 UTC, damianVarela commented on schemas/feed.schema.json
> +  "$id": "https://region-registry.skedgo.com/feed.schema.json",
done -> https://github.com/skedgo/regions/pull/4/commits/358fbf94657ca3e0f7cff71a9ae00341777d9655

2022-09-07 19:11 UTC, damianVarela commented on schemas/region.schema.json
> +          "additionalProperties": false
Alright! After doing some testing, I found out that this property is something different than I thought it was. I removed it and in my testing works well when I provide a polygon in there.

2022-09-08 23:01 UTC, nighthawk commented on schemas/region.schema.json
> +          "description": "Latitude coordinate.",
Should we specify the coordinate format, i.e., [WGS-84](https://epsg.org/crs_4326/WGS-84.html)?

2022-09-08 23:01 UTC, nighthawk commented on schemas/region.schema.json
> +        "polygon": {
Can we add a description to this that no cutouts are not allowed?

2022-09-09 12:09 UTC, damianVarela commented on schemas/feed.schema.json
> +      "description": "Unique identifier for this feed.",
are you fine with last changes about this? can we mark this one as resolved if that's the case?

2022-09-09 12:49 UTC, damianVarela commented on schemas/public-transport-feed.schema.json
> +      "properties": {
I guess you mean to have this `license` field but in a feed level, not within the `source` object. i added such field in https://github.com/skedgo/regions/pull/4/commits/905fa71914490b1a56b8072bf5e6fdb4a1d0ee24 . all inner fields (name and url) are required as requested. should the `license` field itself be required as well?

2022-09-09 12:50 UTC, damianVarela commented on schemas/region.schema.json
> +          "description": "Latitude coordinate.",
done -> https://github.com/skedgo/regions/pull/4/commits/a07d1e9bc79510298c341776f01e9363dad8a75d

2022-09-09 12:54 UTC, damianVarela commented on schemas/region.schema.json
> +        "polygon": {
done -> https://github.com/skedgo/regions/pull/4/commits/aa78aafe6051bac50ac406273c0d8945c393445f 

i'm not quite sure what you mean with "cutouts". but perhaps it's not a relevant thing that it should be clear to me.

2022-09-09 15:11 UTC, damianVarela commented on schemas/public-transport-feed.schema.json
> +      "required": [ "url" ]
hmmm. kinda weird to have it within the source object. can we move to root?

2022-09-10 00:05 UTC, nighthawk commented on schemas/region.schema.json
> +        "polygon": {
https://www.rfc-editor.org/rfc/rfc7946#section-3.1.6 => "interior rings". Say South Africa's area is a polygon, with Lesotho being removed. This is not allowed here.

2022-09-10 04:55 UTC, nighthawk commented on schemas/real-time-data-feed.schema.json
> +    },
Would be good to add an additional `subtype`, e.g., for GTFS-R it tells you if this feed has time-table updates, vehicles, or alerts. Might be an "enum set"? Not sure if a GTFS-R feed can have multiple of these.

For SIRI it would be whether it's SIRI-SX, or all those different types.

2022-09-10 04:55 UTC, nighthawk commented on schemas/real-time-data-feed.schema.json
> +      "pattern": "^(([A-Z]|[a-z]|-|_)+)$"
Why doesn't this allow spaces or numbers? Why limit it at all for that matter?

```suggestion
      "minLength": 1
```

2022-09-10 04:55 UTC, nighthawk commented on schemas/real-time-data-feed.schema.json
> +  "required": [ "id", "name", "source" ]
Another very useful feed for real-time feeds would be "refreshIntervals" i.e., how many seconds between pulling that information.

For SIRI there are also different supported ways of consuming it. Polling, pub/sub, and some others, if I recall correctly. Would be good to add to the specs, too.

2022-09-10 04:55 UTC, nighthawk commented on schemas/public-transport-feed.schema.json
> +      "pattern": "^(([A-Z]|[a-z]|-|_)+)$"
See below. I'd remove the pattern.

```suggestion
      "minLength": 1
```

2022-09-10 04:55 UTC, nighthawk commented on schemas/public-transport-feed.schema.json
> +  "$id": "https://region-registry.skedgo.com/public-transport-feed.schema.json",
Should we rename this `pt-static-feed.schema.json` and the real-time on `pt-realtime-feed.schema.json`?

2022-09-10 04:55 UTC, nighthawk commented on schemas/public-transport-feed.schema.json
> +          "description": "Information about the API where this feed is published.",
From the name and description, I don't understand what this is. Do you have an example?

2022-09-12 13:10 UTC, damianVarela commented on schemas/region.schema.json
> +        "polygon": {
mmmm. i see... you mean like enclaves. Aren't we already restraining that by asking a Polygon instead of a MultiPolygon ? Can a GeoJSON Polygon have holes in it?

2022-09-12 14:35 UTC, damianVarela commented on schemas/real-time-data-feed.schema.json
> +    },
@nighthawk wrote:
> Not sure if a GTFS-R feed can have multiple of these.

I just asked @fersagui and @fede843 and they explained to me that this could happen and we also have support for this kind of situations. So, yes, it should be an array.

I've added a required `subtype` field which is an array where its items are conditionally valid based on the value of the `type` field. 
- If it is `gtfs-r`, then the `subtype` valid items can be `trip-updates`, `alerts` or `vehicle-positions`. 
- If it is `siri`, then the `subtype` valid items can be `et`,`sx`,`vm`. 

all this is done in here -> https://github.com/skedgo/regions/pull/4/commits/9f51da5fd9933dc36972077b6796c231de25abc3

2022-09-12 15:43 UTC, damianVarela commented on schemas/real-time-data-feed.schema.json
> +  "required": [ "id", "name", "source" ]
@nighthawk wrote:
>Another very useful feed for real-time feeds would be "refreshIntervals" i.e., how many seconds between pulling that information.

done -> https://github.com/skedgo/regions/pull/4/commits/9f269bfc8b251e6001ef95da1e1ebb82bead6a0e

>For SIRI there are also different supported ways of consuming it. Polling, pub/sub, and some others, if I recall correctly. Would be good to add to the specs, too.

done -> https://github.com/skedgo/regions/pull/4/commits/a68add485aad07cdef99ff27b2fcf5cd08a94ed9

2022-09-12 16:05 UTC, damianVarela commented on schemas/region.schema.json
> +        "polygon": {
Ok, I just checked on this. And Polygons can have holes in it. I thought that could only happen with MultiPolygons. Here's an example -> https://gist.githubusercontent.com/andrewharvey/971b9db1900a62efa7635f6a6d337ae7/raw/de8f54ab665beafcfc8b6a55c90e278fd25de659/polygon-with-a-hole.geojson

I see that GeoJSON Polygon is an array of Polygons, so there is the possibility of holes. I override this to require one and only one polygon. Is that ok/enough? See -> https://github.com/skedgo/regions/pull/4/commits/076f67bf6fd074a99e15cec4bdca99b9c656b761

2022-09-12 16:07 UTC, damianVarela commented on schemas/public-transport-feed.schema.json
> +      "description": "Real time feeds associated to this feed. Each item should match with a real-time-feed id.",
defined here -> https://github.com/skedgo/regions/pull/4/commits/ece6c8855f1f1ccccc26ee5d13055ffae032e9b9

2022-09-12 16:13 UTC, damianVarela commented on schemas/public-transport-feed.schema.json
> +          "description": "Information about the API where this feed is published.",
This is for have a handy way to go to the website that actually provides the open data, links for gtfs, api information, etc. For example, here we put 
https://dipl.nt.gov.au/data/bus-timetable-data-and-geographic-information instead of https://dipl.nt.gov.au/

We can remove all this if you want.

2022-09-12 16:16 UTC, damianVarela commented on schemas/public-transport-feed.schema.json
> +  "$id": "https://region-registry.skedgo.com/public-transport-feed.schema.json",
done -> https://github.com/skedgo/regions/pull/4/commits/0f0a3da77421c894023ef829a1d63697acc73a6f

2022-09-12 21:33 UTC, nighthawk commented on schemas/region.schema.json
> +        "polygon": {
Great, looks good.

2022-09-12 21:33 UTC, nighthawk approved these changes
I'm happy with it. Let's roll with it and see how it goes when we add the first regions.

2022-09-12 21:33 UTC, merged

2022-09-12 21:34 UTC, nighthawk commented on schemas/public-transport-feed.schema.json
> +          "description": "Information about the API where this feed is published.",
Great idea, let's keep it.