#1800 regions/us co western
skedgo/regions pull request #5
Opened 2022-09-13 18:32 UTC by ManuBenito259

Added the us_co_western region, and it's static provider us_veiltransit

2022-09-13 18:56 UTC, damianVarela requested changes

2022-09-13 18:56 UTC, damianVarela commented on regions/us_co_western.json
> +      "coordinates": [
coordinates must follow [GeoJSON schema for Polygons](https://geojson.org/schema/Polygon.json). Please, wrap the `coordinates` array into another array.

```json
"coordinates": [
    [
        [0.0, 0.0]
    ]
]
```

2022-09-13 18:56 UTC, damianVarela commented on regions/us_co_western.json
> +      "lng": -106.340538,
Please, make sure these coordinates are contained in the coverage.polygon, otherwise, validator will fail.

2022-09-13 19:16 UTC, ManuBenito259 commented on regions/us_co_western.json
> +      "coordinates": [
I didn't notice, fixed!

2022-09-13 20:35 UTC, fersagui requested changes

2022-09-13 20:35 UTC, fersagui commented on regions/us_co_western.json
> +    "cityName": "Vail"
"Vail" is a small town. The region name should have a bigger city, a [county](https://en.wikipedia.org/wiki/List_of_counties_in_Colorado) or a name which defines a portion of the state, like "Western"

2022-09-13 20:35 UTC, fersagui commented on regions/us_co_western.json
> +                  [-106.351887,39.6396260000001]
Polygon is too small. Would be better to increase the size to be next to the Denver polygon area.

2022-09-14 14:39 UTC, damianVarela approved these changes
approved as long as validator doesn't fail.

2022-09-14 15:38 UTC, fersagui commented on regions/us_co_western.json
> +    "cityName": "Vail"
I have double checked and there no big cities there so it is ok to use "Vail"

2022-09-16 01:17 UTC, nighthawk commented on regions/us_co_western.json
> +    "cityName": "Vail"
@damianVarela Should this match the file name? The file name is `us_co_western` but this implies `US_CO_Vail`. Might be confusing to have both?

2022-09-16 13:02 UTC, fersagui requested changes
The polygon should be changed

2022-09-16 16:16 UTC, damianVarela commented on regions/us_co_western.json
> +    "cityName": "Vail"
@nighthawk wrote:

>Should this match the file name? The file name is us_co_western but this implies US_CO_Vail. Might be confusing to have both?

i was wondering about that. there's no specs related to the file name. in the end, it doesn't matter how the files are named, we would be dealing just with the content. nevertheless, i would prefer to have the all the file names with the same case and to use hyphens instead of underscores. we can modify the validator to accept files like that and also we can add a rule that the name must in the format `countryCode`[-`subdivisionCode` if any]-`cityName`.json all in lowercase with no spaces. 

thoughts?

2022-09-16 17:19 UTC, fersagui commented on regions/us_co_western.json
> +    "cityName": "Vail"
I like the idea. I also prefer the hyphens as the naming convention. My vote is to use this convention.

2022-09-19 19:03 UTC, fersagui approved these changes
LGTM

2022-09-19 22:38 UTC, merged