#1800/regions/us nc northern
skedgo/regions pull request #7
Opened 2022-09-15 21:48 UTC by ManuBenito259

2022-09-16 13:34 UTC, fersagui requested changes

2022-09-16 13:34 UTC, fersagui commented on regions/us_nc_northern.json
> +    }},
I would not go to near Charlotte if we do not cover that complete and I think it should cover well Raleigh to the east side.

2022-09-16 19:51 UTC, ManuBenito259 commented on regions/us_nc_northern.json
> +    }},
Im trying to avoid Charlotte but I understand we need Concord and Kannapolis to include Rider Transport so theres not much room to it

2022-09-20 11:46 UTC, fersagui approved these changes

2022-09-20 11:48 UTC, merged