us_la_western
skedgo/regions pull request #8
Opened 2022-09-15 21:59 UTC by ManuBenito259

Added the LA Western region and its static feed Sportran

2022-09-16 01:29 UTC, nighthawk commented on regions/us_la_western.json
> +{
File name should use `-` not `_`

2022-09-16 01:34 UTC, nighthawk commented on regions/us_la_western.json
> +      "type": "Polygon",
This polygon is oddly narrow and very tall. Should be save to extend East to include Natchitoches to allow for car + PT results coming from there.

<img width="600" alt="Screen Shot 2022-09-16 at 11 33 41" src="https://user-images.githubusercontent.com/22646/190537363-eb720853-7f11-4a2c-8096-373a799d6466.png">

2022-09-16 13:17 UTC, fersagui requested changes

2022-09-16 13:17 UTC, fersagui commented on regions/us_la_western.json
> +        "lng": 93.714752,
This is wrong

2022-09-16 13:17 UTC, fersagui commented on regions/us_la_western.json
> +      "type": "Polygon",
Yes, agree. Let's make this one bigger to cover the surrounding cities.

2022-09-16 17:24 UTC, fersagui commented on regions/us_la_western.json
> +        "lng": 93.714752,
```suggestion
        "lng": -93.714752,
```

2022-09-17 05:19 UTC, nighthawk commented on regions/us-la-shreveport.json
> +  "timezone": "America/New_York",
Is this correct? This region is very much in the centre of the US. Is that still NY timezone?

2022-09-19 14:54 UTC, ManuBenito259 commented on regions/us-la-shreveport.json
> +  "timezone": "America/New_York",
Its not, its actually Chicago, fixing it right away

2022-09-19 18:28 UTC, fersagui commented on regions/us-la-shreveport.json
> +  "timezone": "America/New_York",
@damianVarela I really like your idea. 

> a region can have only one timezone, right?

A default one must be set. The idea is to creation which are always in the same timezone. Only the super region could have more.

2022-09-19 18:37 UTC, fersagui commented on regions/us-la-shreveport.json
> +      "name": "Shreveport"
The full name with state and country is "Shreveport, LA, US". 

@nighthawk make sense to use simple city names here or the complete ones are mandatory for the geocoder?

2022-09-19 21:22 UTC, nighthawk commented on regions/us-la-shreveport.json
> +      "name": "Shreveport"
It should use the simple name here. The full one can be built using what's in `code` at the top level.

2022-09-19 21:48 UTC, fersagui approved these changes

2022-09-19 21:49 UTC, merged